CREATE DATABASE EZ3YRC;
USE EZ3YRC;
CREATE TABLE TANFOLYAM(tkod INT, ar INT CHECK(ar>0), tipus CHAR(20), megnevezes CHAR(20), PRIMARY KEY(tkod));
CREATE TABLE RESZTVEVO(tajszam INT, nev CHAR(30) NOT NULL, lakcim CHAR(40), PRIMARY KEY (tajszam));
CREATE TABLE BEFIZETES(tanfolyamok INT REFERENCES TANFOLYAM, resztvevok INT REFERENCES RESZTVEVO, befizetes INT);