CREATE DATABASE EZ3YRC;
USE EZ3YRC;
INSERT INTO TULAJDONOS VALUES(101,'Kis János','Miskolc');
INSERT INTO TULAJDONOS VALUES(102,'Kis Éva','Szerencs');
INSERT INTO TULAJDONOS VALUES(103,'Retek Ödön','Miskolc');
INSERT INTO TULAJDONOS VALUES(104,'Virág Zoltán','Nyék');
INSERT INTO TULAJDONOS VALUES(105,'Nagy Eszter','Nyék');
INSERT INTO TULAJDONOS VALUES(106,'Kovács Magor','Szerencs');
INSERT INTO TULAJDONOS VALUES(107,'Asztal Antal','Miskolc');