CREATE DATABASE EZ3YRC;
USE EZ3YRC;
SELECT AUTO.TÍPUS, AVG(ar) FROM AUTO
GROUP BY AUTO.TÍPUS
HAVING AVG(AR) > 500;

SELECT DISTINCT AUTO.TÍPUS, COUNT(típus) FROM AUTO
WHERE AUTO.SZÍN = 'Piros'
ORDER BY AUTO.TÍPUS;

SELECT COUNT(rendszam) FROM AUTO;

SELECT AUTO.RENDSZAM FROM AUTO
WHERE szín = 'Piros' OR szín = 'Kék' OR szín = 'Fehér';

SELECT AUTO.AR *399 FROM AUTO;

SELECT AUTO.RENDSZAM, TULAJDONOS.NEV FROM AUTO
JOIN TULAJDONOS ON AUTO. TULAJ = TULAJDONOS.TKOD;

SELECT * FROM AUTO
JOIN TULAJDONOS ON AUTO.TULAJ = TULAJDONOS.TKOD
WHERE TULAJDONOS.VAROS = 'Miskolc';

SELECT DISTINCT AUTO.TÍPUS, AUTO.AR, AUTO.SZÍN FROM AUTO;

SELECT TULAJDONOS.NEV, AUTO.TÍPUS FROM TULAJDONOS
JOIN AUTO ON AUTO.TULAJ = TULAJDONOS.TKOD;

SELECT AUTO.RENDSZAM, TULAJDONOS.NEV FROM AUTO
JOIN TULAJDONOS ON AUTO.TULAJ = TULAJDONOS.TKOD;

SELECT AUTO.RENDSZAM, AVG(AR) FROM AUTO
JOIN TULAJDONOS ON AUTO.TULAJ = TULAJDONOS.TKOD
WHERE TULAJDONOS.VAROS != 'Miskolc'
GROUP BY AUTO.RENDSZAM
HAVING AUTO.AR > AVG(AR);

SELECT TULAJDONOS.NEV, COUNT(rendszam) FROM AUTO
JOIN TULAJDONOS ON AUTO.TULAJ = TULAJDONOS.TKOD
GROUP BY TULAJDONOS.NEV
HAVING COUNT(rendszam) > 1;







SELECT * FROM AUTO
WHERE AUTO.SZÍN != 'Piros';






SELECT TULAJDONOS.NEV FROM TULAJDONOS
JOIN AUTO ON AUTO.TULAJ = TULAJDONOS.TKOD
WHERE AUTO.TULAJ IS NULL;



SELECT TULAJDONOS.NEV FROM TULAJDONOS
JOIN AUTO ON AUTO.TULAJ = TULAJDONOS.TKOD
WHERE AUTO.TULAJ IS NOT NULL;
